# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Daan Bakboord
description: "Hi I'm Daan, and I'm a Data Enthusiast.  My passion is collecting, processing, storing and presenting data. I help organizations to use this internal and external data in such a way that they can take action. My goal is simple. A customer must be able to make decisions based on facts in the right context. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "https://www.daanalytics.nl/blogs" # the subpath of your site, e.g. /blog
url: "https://www.daanalytics.nl" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Rotterdam, NL"
resume_url: /docs/06.2021 CV NL Daan Bakboord DaAnalytics.pdf
avatar_image: /img/Daan Bakboord - DaAnalytics - headshot.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/in/daanbakboord" # Add your linkedln handle
github: "https://github.com/daanalytics"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

